"""
Django settings for vispro project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rzkh6d0b+*@1xr=xlx7q1ugzfn39h6fq%5xe%qgwd2q=f(l!bf'
'''
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY is not set")

from django.core.management.utils import get_random_secret_key
get_random_secret_key()
setx DJANGO_SECRET_KEY "django-insecure--_+4p#b!%hd-8^^z0kz$&c=*jh+%v-1kmu1@)di^puzc2kvt#gt"
echo $env:DJANGO_SECRET_KEY
'''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
'''
python.exe -m pip install --upgrade pip
python -m pip list
python -m pip install mysql-connector-python
python -m pip install mysqlclient
python -m pip install djangorestframework
python -m pip install djangorestframework-simplejwt
python -m pip install django-filter
python -m pip install drf-spectacular
'''
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',

    # Local apps
    'api',
    'cbv',
    'fbv',
    'kavi',
]

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_VERSIONING_CLASS':
        'rest_framework.versioning.QueryParameterVersioning',
        # 'rest_framework.versioning.AcceptHeaderVersioning',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [  # Only the LAST one survives
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'Detail':'3/minute',
        'Detail-list': '2/minute',
        'Detail-detail': '3/minute',
        'anon': '5/minute',      # Anonymous users: 5 requests per minute
        'user': '7/minute'       # Authenticated users: 100 requests per hour
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination', # ?limit=5&offset=10
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination', # ?cursor=abc123
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.CustomPageNumberPagination',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination', # ?page=2
    'PAGE_SIZE': 5,

    # version
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning', # (Most Common)
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.HostNameVersioning",
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning', # header Accept: application/json; version=2.0
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.QueryParameterVersioning', # (Advanced), # /api/?version=1
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'VERSION_PARAM': 'version',

    # exception handling
    'EXCEPTION_HANDLER': 'api.utils.custom_exception_handler',
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-cache-name',
    }
}
'''
CACHES = {  # pip install django-redis
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}'''

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kavi.middleware.authredirectmiddleware',
    'cbv.middleware.authredirectmiddleware',
    'vispro.middleware.logging.LoggingMiddleware',
    'vispro.middleware.logging.RequestLoggingMiddleware',
    'vispro.middleware.logging.SimpleLogMiddleware',
]
"""
# Important Built-in Middleware (Know These)
SecurityMiddleware,
SessionMiddleware,
CsrfViewMiddleware,
AuthenticationMiddleware.

Middleware runs 
top → bottom on request, 
bottom → top on response.
"""

ROOT_URLCONF = 'vispro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vispro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vis',
        'USER': 'root',
        'PASSWORD': 'Kaviya18.',  # os.getenv("DB_PASSWORD"),
        'HOST': 'localhost',
        'PORT': '3306',
        'ATOMIC_REQUESTS': False,  # if false per-view, if true Entire site
    }
}
'''
    ATOMIC_REQUESTS = False

    @transaction.atomic
    def my_view(request):
        ...
    # You can use @transaction.atomic without ATOMIC_REQUESTS.
'''

AUTH_USER_MODEL = 'kavi.Auser'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "kavi/static",
    BASE_DIR/ "cbv/static"
]

LOGIN_REDIRECT_URL = 'cbv:home'
LOGOUT_REDIRECT_URL = 'cbv:login'
LOGIN_URL = 'cbv:login'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# or MEDIA_ROOT = BASE_DIR / 'media'


ADMINS = [
    ('Admin', 'admin@example.com'),
]

# `django.log`      - General application logs               
# `errors.log`      - Exceptions & 500 errors                
# `security.log`    - CSRF, SuspiciousOperation, auth issues 
# `performance.log` - Slow queries, execution timing

'''
"simple": {
    "format": "{levelname}: {message}",
    "style": "{",
},
"json": {  # pip install python-json-logger
    "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
    "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
},
'''

LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
'''
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # -------------------------
    # FILTERS
    # -------------------------
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },

    # -------------------------
    # FORMATTERS
    # -------------------------
    "formatters": {
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
        "standard": {
            "format": "[{asctime}] [{levelname}] {name}:{lineno} - {message}",
            "style": "{",
        },
        "verbose": {
            "format": (
                "[{asctime}] [{levelname}] "
                "[{process:d}] [{thread:d}] "
                "{name}:{lineno} - {message}"
            ),
            "style": "{",
        },
    },

    # -------------------------
    # HANDLERS
    # -------------------------
    "handlers": {
        # Console → DEVELOPMENT ONLY
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["require_debug_true"],
            "level": "DEBUG",
        },

        # General Django logs (PRODUCTION)
        "django_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "django.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "standard",
            "filters": ["require_debug_false"],
            "level": "INFO",
        },

        # Errors only
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "errors.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "filters": ["require_debug_false"],
            "level": "ERROR",
        },

        # Security events
        "security_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "security.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "standard",
            "filters": ["require_debug_false"],
            "level": "WARNING",
        },

        # Performance / timing
        "performance_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "performance.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "standard",
            "filters": ["require_debug_false"],
            "level": "INFO",
        },

        # Email admins on crashes (PRODUCTION)
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "level": "ERROR",
        },
    },

    # -------------------------
    # LOGGERS
    # -------------------------
    "loggers": {
        # Core Django logs
        "django": {
            "handlers": ["console", "django_file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },

        # Silence noisy autoreload logs
        "django.utils.autoreload": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # HTTP 500 errors
        "django.request": {
            "handlers": ["error_file", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },

        # Security-related issues
        "django.security": {
            "handlers": ["security_file"],
            "level": "WARNING",
            "propagate": False,
        },

        # Database queries
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },

        # Your project logger
        "visapp": {
            "handlers": ["console", "django_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },

        # Performance logger
        "performance": {
            "handlers": ["performance_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
'''
# Use email logging only for ERROR and CRITICAL events.
# django build-in email logging : django.utils.log.AdminEmailHandler
# Activates only when DEBUG = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@gmail.com'
EMAIL_HOST_PASSWORD = 'your_app_password'  # Never commit real passwords. Use environment variables.
DEFAULT_FROM_EMAIL = 'Server Error <your_email@gmail.com>'
