# Generated by Django 5.2.6 on 2026-01-05 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavi', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='vis', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter your name', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter your name', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('marrital_status', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter your name', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('initial', models.CharField(blank=True, max_length=5, null=True)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('marrital_status', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vis_Member_Created_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('about_creation', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'very_like'), ('B', 'like'), ('C', 'ok'), ('D', 'bad'), ('E', 'very_bad')], default='C', max_length=1, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='kavi.author')),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter your name', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movie_charecter', models.CharField(max_length=50)),
                ('movie_content', models.TextField()),
                ('movie_image', models.ImageField(blank=True, upload_to='posts/images')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavi.category')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vis_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter your name', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='enter your age', null=True)),
                ('lucky_number', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], help_text='select your lucky number')),
                ('about', models.TextField(blank=True, help_text='tell me about yourself', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sleeping_time', models.DurationField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='posts/files')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appa', to='kavi.dad')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amma', to='kavi.mom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vis_table',
                'ordering': ['age'],
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['name'], name='vis_table_name_533c59_idx'), models.Index(fields=['-age'], name='vis_table_age_89263b_idx')],
            },
        ),
    ]
