# Generated by Django 5.2.6 on 2026-01-05 05:27

import cbv.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('age_groups', models.CharField(max_length=50)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'age_group_table',
            },
        ),
        migrations.CreateModel(
            name='All_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField()),
                ('detail_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('initial', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbv.item')),
                ('author', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cbv.item',),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbv.item')),
                ('author', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cbv.item',),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('age', models.IntegerField()),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian phone number starting with 6,7,8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('email_id', models.EmailField(max_length=254, validators=[cbv.models.Email_validator])),
                ('is_active', models.BooleanField(default=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, choices=[('a', 'A grade'), ('b', 'B grade'), ('c', 'C grade'), ('d', 'D grade')], default='d', max_length=50, null=True)),
                ('age_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbv.age_group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Members_Table',
                'ordering': ['age', '-name'],
                'permissions': [('can_publish_detail', 'Can publish detail'), ('can_approve_detail', 'Can approve detail')],
                'get_latest_by': 'age',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExpensiveProduct',
            fields=[
            ],
            options={
                'ordering': ['-price'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cbv.product',),
        ),
        migrations.CreateModel(
            name='ExpensiveBook',
            fields=[
            ],
            options={
                'ordering': ['-price'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cbv.book',),
        ),
    ]
